C:\Program Files (x86)\Arduino\arduino-builder -dump-prefs -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries C:\Users\CESAR\Documents\Arduino\libraries -fqbn=arduino:avr:uno -ide-version=10802 -build-path C:\Users\CESAR\AppData\Local\Temp\arduino_build_956234 -warnings=none -build-cache C:\Users\CESAR\AppData\Local\Temp\arduino_cache_233786 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avr-gcc.path=C:\Program Files (x86)\Arduino\hardware\tools\avr -prefs=runtime.tools.avrdude.path=C:\Program Files (x86)\Arduino\hardware\tools\avr -prefs=runtime.tools.arduinoOTA.path=C:\Program Files (x86)\Arduino\hardware\tools\avr -verbose C:\Users\CESAR\Documents\Arduino\proteus\proteus.ino
C:\Program Files (x86)\Arduino\arduino-builder -compile -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries C:\Users\CESAR\Documents\Arduino\libraries -fqbn=arduino:avr:uno -ide-version=10802 -build-path C:\Users\CESAR\AppData\Local\Temp\arduino_build_956234 -warnings=none -build-cache C:\Users\CESAR\AppData\Local\Temp\arduino_cache_233786 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avr-gcc.path=C:\Program Files (x86)\Arduino\hardware\tools\avr -prefs=runtime.tools.avrdude.path=C:\Program Files (x86)\Arduino\hardware\tools\avr -prefs=runtime.tools.arduinoOTA.path=C:\Program Files (x86)\Arduino\hardware\tools\avr -verbose C:\Users\CESAR\Documents\Arduino\proteus\proteus.ino
Using board 'uno' from platform in folder: C:\Program Files (x86)\Arduino\hardware\arduino\avr
Using core 'arduino' from platform in folder: C:\Program Files (x86)\Arduino\hardware\arduino\avr
Detecting libraries used...
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10802 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "C:\Users\CESAR\AppData\Local\Temp\arduino_build_956234\sketch\proteus.ino.cpp" -o "nul"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10802 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "-IC:\Users\CESAR\Documents\Arduino\libraries\TinyGPS-13" "C:\Users\CESAR\AppData\Local\Temp\arduino_build_956234\sketch\proteus.ino.cpp" -o "nul"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10802 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "-IC:\Users\CESAR\Documents\Arduino\libraries\TinyGPS-13" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\SoftwareSerial\src" "C:\Users\CESAR\AppData\Local\Temp\arduino_build_956234\sketch\proteus.ino.cpp" -o "nul"
Using cached library dependencies for file: C:\Users\CESAR\Documents\Arduino\libraries\TinyGPS-13\TinyGPS.cpp
Using cached library dependencies for file: C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\SoftwareSerial\src\SoftwareSerial.cpp
Generating function prototypes...
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10802 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "-IC:\Users\CESAR\Documents\Arduino\libraries\TinyGPS-13" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\SoftwareSerial\src" "C:\Users\CESAR\AppData\Local\Temp\arduino_build_956234\sketch\proteus.ino.cpp" -o "C:\Users\CESAR\AppData\Local\Temp\arduino_build_956234\preproc\ctags_target_for_gcc_minus_e.cpp"
"C:\Program Files (x86)\Arduino\tools-builder\ctags\5.8-arduino11/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "C:\Users\CESAR\AppData\Local\Temp\arduino_build_956234\preproc\ctags_target_for_gcc_minus_e.cpp"
Compilando programa...
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10802 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "-IC:\Users\CESAR\Documents\Arduino\libraries\TinyGPS-13" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\SoftwareSerial\src" "C:\Users\CESAR\AppData\Local\Temp\arduino_build_956234\sketch\proteus.ino.cpp" -o "C:\Users\CESAR\AppData\Local\Temp\arduino_build_956234\sketch\proteus.ino.cpp.o"
Compiling libraries...
Compiling library "TinyGPS-13"
Utilizando archivo previamente compilado: C:\Users\CESAR\AppData\Local\Temp\arduino_build_956234\libraries\TinyGPS-13\TinyGPS.cpp.o
Compiling library "SoftwareSerial"
Utilizando archivo previamente compilado: C:\Users\CESAR\AppData\Local\Temp\arduino_build_956234\libraries\SoftwareSerial\SoftwareSerial.cpp.o
Compiling core...
Using precompiled core
Linking everything together...
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-gcc" -w -Os -g -flto -fuse-linker-plugin -Wl,--gc-sections -mmcu=atmega328p  -o "C:\Users\CESAR\AppData\Local\Temp\arduino_build_956234/proteus.ino.elf" "C:\Users\CESAR\AppData\Local\Temp\arduino_build_956234\sketch\proteus.ino.cpp.o" "C:\Users\CESAR\AppData\Local\Temp\arduino_build_956234\libraries\TinyGPS-13\TinyGPS.cpp.o" "C:\Users\CESAR\AppData\Local\Temp\arduino_build_956234\libraries\SoftwareSerial\SoftwareSerial.cpp.o" "C:\Users\CESAR\AppData\Local\Temp\arduino_build_956234/..\arduino_cache_233786\core\core_arduino_avr_uno_0c812875ac70eb4a9b385d8fb077f54c.a" "-LC:\Users\CESAR\AppData\Local\Temp\arduino_build_956234" -lm
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-objcopy" -O ihex -j .eeprom --set-section-flags=.eeprom=alloc,load --no-change-warnings --change-section-lma .eeprom=0  "C:\Users\CESAR\AppData\Local\Temp\arduino_build_956234/proteus.ino.elf" "C:\Users\CESAR\AppData\Local\Temp\arduino_build_956234/proteus.ino.eep"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-objcopy" -O ihex -R .eeprom  "C:\Users\CESAR\AppData\Local\Temp\arduino_build_956234/proteus.ino.elf" "C:\Users\CESAR\AppData\Local\Temp\arduino_build_956234/proteus.ino.hex"
Utilizando biblioteca TinyGPS-13 en carpeta: C:\Users\CESAR\Documents\Arduino\libraries\TinyGPS-13 (legacy)
Usando librería SoftwareSerial con versión 1.0 en la carpeta: C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\SoftwareSerial 
El Sketch usa 8066 bytes (25%) del espacio de almacenamiento de programa. El máximo es 32256 bytes.
Las variables Globales usan 504 bytes (24%) de la memoria dinámica, dejando 1544 bytes para las variables locales. El máximo es 2048 bytes.